### ISSUE TITLE
Allow async module deletes

### ISSUE THREAD

**Issue by merrill-oakland** [moodlehq/moodle-tool_migratehvp2h5p#14]
In tool_migratehvp2h5p\finish_migration, course_delete_module() is called, but the async parameter isn't passed, meaning the tool call itself has to wait for the delete, which itself isn't too bad, but if you have the recycle bin on (which is default), it also has to wait for a backup to be completed first. This takes *forever* on large sites.

Personally, I think we should be calling course_delete_module() with async true, or at least expose an option to do that. The original course module will instantly be removed as deleted to users, and adhoc tasks from recycle bin then do that background work of backing up/actually deleting them.

**Comment by sarjona** [comment]
Thanks a lot for the suggestion, Eric! 
I agree with you that $async parameter will help to improve performance and, as I can't see any benefit of adding it as a setting for the plugin, I've changed it to true in the code.

If anybody has any reason for having it as a setting, I'll be happy to create it but, for now, I think is better to set it to true in order to keep the plugin as simple as we can.
