### ISSUE TITLE
Option to migrate only a given content type / a subset of content types

### ISSUE THREAD

**Issue by abias** [moodlehq/moodle-tool_migratehvp2h5p#19]
Hi @sarjona ,

as an admin, I would like to be able to migrate only a given content type / a subset of content types with this tool within a bulk CLI operation and / or an easy GUI widget.

This will be much helpful if you have a Moodle instance where mod_hvp was run with all content types (like we have), but you want to restrict the number of available content types now during migrating to the Moodle core integration and want to migrate just the content which you will support in the long run.

This will also be helpful if you have a large amount of existing content to migrate, but want to schedule the migration by content types instead of by chunks of 100 H5P instances.

Thanks in advance,
Alex

**Comment by sarjona** [comment]
Alexander, thanks a lot for the suggestion. 
I've added a parameter to CLI to let admins specify a list of library ids ;-)

I haven't changed anything in GUI because, as admins can filter by "Content type" column (and now they can use the new CLI option), they have a workaround for the use case you explain if required ;-)
