### ISSUE TITLE
Activity not migrated when contentbank repository is disabled

### ISSUE THREAD

**Issue by sarjona** [moodlehq/moodle-tool_migratehvp2h5p#29]
Thanks @adpe for raising this in https://github.com/moodlehq/moodle-tool_migratehvp2h5p/issues/15#issuecomment-769679615

I've been able to reproduce it and I'm working on a patch.

**Comment by adpe** [comment]
Thank you very much @sarjona 

The patch was already helpful, and we faced then other errors. Thus, was because we had apart from the content bank `repository`, the H5P `content bank type` and `mod_h5pactivity` disabled as well. So it was still failing.

It will be good for other users, if you can add here some further checks and display error messages. Then the user should know what is missing, to finally run the migration with success!

Should you add also some information about it in the `documentation`?

Greets
Adrian

**Comment by sarjona** [comment]
Thanks a lot for your time and suggestions, Adrian!
I've just added a commit to improve that part (and avoid other people face the same issues you found last week): https://github.com/moodlehq/moodle-tool_migratehvp2h5p/pull/32

**Comment by adpe** [comment]
Hi @sarjona 

The migration was smooth and all worked as expected

Thanks again
Adrian

**Comment by sarjona** [comment]
Yupiiiiiii! I'm glad to hear you were able to migrate all the H5P activities! :-)
